### ISSUE TITLE
Plugin does not work with larger amounts of users/comments.

### ISSUE THREAD

**Issue by NielsIH** [baldogiRichard/apex-comments#1]
Hi,

When there are a couple of hundred comments or users the plugin does not work. (PL/sql error).
The problem is because the apex_javascript.add_onload_code parameter p_code is varchar2 and limited in size.
It's not suitable to directly pass large JSON structures into this procedure.

The comments and users arrays need to be fetched through ajax after initialization.

**Comment by baldogiRichard** [comment]
Hi,

Thank you for your feedback. In the future I will include 2 options:

Attribute name is going to be: Lazy load

Options (checkbox list): 

- Pinging list
- Comments

In case of comments there will be a new div html region which can be used
to load comments if comments option is checked. The implementation should look
something like this:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/100072414/202514589-00b154db-0a3c-485c-ba53-e3bf75ee871b.png">

Richard

**Comment by baldogiRichard** [comment]
Added a new procedure to the plug-ins "splitJSON" which helps to overpass the varchar2 limit in the apex_javascript.add_onload_code procedure p_code parameter by adding a splitted and escaped JSON variable before the onload code.
